version: '3.8'
name: 'java_forum'
services:
  java:
    build:
      context: ./
      dockerfile: docker/java.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www:cached
    expose:
      - "8080"
    ports:
      - "8080:8080" 
  database:
    platform: linux/x86_64
    image: mysql:8.0.31
    volumes:
      - dbdata:/var/lib/mysql:delegated
    environment:
      - "MYSQL_DATABASE=forum"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
      - "3306:3306"

# before build docker network create "java_forum"
networks:
  default:
    name: java_forum
    external: true

volumes:
  dbdata: